#!/usr/bin/python

# This script contains custom dictionaries for FSE stuff
# Selected aircraft types have their ICAO code listed for easy reference in other scripts
# In duplicate cases a letter "i" is generally added
# All countries for FSE airports are also listed with a corresponding region

def getactypedict():
	dict={"LA60": "Aermacchi - Lockheed AL-60",
	"AC50": "Aero Design AC500C",
	"AC68": "Aero Design AC680S",
	"AC90": "Aero Design AC690",
	"L39": "Aero Vodochody L-39",
	"CH7A": "Aeronca Champion",
	"A109": "Agusta A109",
	"A320": "Airbus A320",
	"A321": "Airbus A321",
	"AS57": "Airspeed AS-57 Ambassador ",
	"C27J": "Alenia C-27J Spartan",
	"C27Ji": "Alenia C-27J Spartan (IRIS)",
	"BL8": "American Champion Scout",
	"AN14": "Antonov An-14",
	"AN2": "Antonov AN-2",
	"AN24": "Antonov An-24",
	"AN26": "Antonov An-26 Curl",
	"AN28": "Antonov An-28",
	"AN32": "Antonov An-32",
	"AT45": "ATR 42-500",
	"AT75": "ATR 72-500",
	"J1": "Auster J/1 Autocrat",
	"NOMA": "Australia GAF N22 Nomad",
	"HUSK": "Aviat A-1 Husky",
	"ANSN": "Avro Anson MK-1",
	"JPRO": "BAC Jet Provost T5",
	"B461": "BAe 146-100 (Avro RJ70)",
	"JS32": "BAe Jetstream 32",
	"JS41": "BAe Jetstream 41",
	"DC3T": "Basler BT-67",
	"BASS": "Beagle B 206 Basset",
	"BE33": "Beech Debonair",
	"B80S": "Beech Queen Air 80S",
	"T34P": "Beech T-34 Mentor",
	"BE17": "Beechcraft 17",
	"BE18": "Beechcraft 18",
	"B190C": "Beechcraft 1900C",
	"B190F": "Beechcraft 1900C Freighter",
	"B190D": "Beechcraft 1900D",
	"BE58": "Beechcraft Baron 58",
	"BE58i": "Beechcraft Baron 58 - tip tanks (Dreamfleet)",
	"BE36": "Beechcraft Bonanza A36",
	"BE33": "Beechcraft Bonanza F33",
	"BE35": "Beechcraft Bonanza V35",
	"BE76": "Beechcraft Duchess 76",
	"BE60": "Beechcraft Duke B60",
	"BE20": "Beechcraft King Air 200",
	"BE30": "Beechcraft King Air 300",
	"B350": "Beechcraft King Air 350",
	"BE9L": "Beechcraft King Air C90",
	"BE80": "Beechcraft Queen Air",
	"B60T": "Beechcraft Royal Turbine Duke B60",
	"BE50": "Beechcraft Twin Bonanza 50",
	"UH1": "Bell 205A-1/UH-1C",
	"B06": "Bell 206B",
	"B06L": "Bell 206L RTW N3911Z",
	"B212": "Bell 212",
	"B407": "Bell 407",
	"B412": "Bell 412",
	"B430": "Bell 430",
	"B430": "Bell 430 RTW N430Q",
	"B47G": "Bell 47G-2",
	"UH1": "Bell UH-1H Huey",
	"B14C": "Bellanca 260",
	"B103": "Beriev BE-103",
	"B377": "Boeing 377",
	"B722": "Boeing 727-100/200",
	"B738": "Boeing 737-800",
	"B17G": "Boeing B-17G",
	"ST75": "Boeing Stearman",
	"CH47": "Boeing Vertol CH-47 Chinook",
	"CL30": "Bombardier Challenger 300",
	"CL2T": "Bombardier CL-415",
	"CRJ2": "Bombardier CRJ-200ER",
	"CRJ7": "Bombardier CRJ700-ER",
	"DH8D": "Bombardier Dash-8 Q400",
	"LJ60": "Bombardier Lear 60",
	"BR30": "Bristol Britannia 300",
	"BN2T": "Britten Norman BN-2A Mk3-3 Trislander",
	"BN2P": "Britten-Norman BN-2B Islander",
	"BU31": "Bucker Jungmann 131",
	"CN35": "CASA CN235",
	"C152": "Cessna 152 Aerobat",
	"C162": "Cessna 162 Skycatcher",
	"C172": "Cessna 172 Skyhawk",
	"C177": "Cessna 177 Cardinal",
	"C177r": "Cessna 177RG Cardinal",
	"C182": "Cessna 182 Skylane",
	"C185": "Cessna 185 Skywagon",
	"C195": "Cessna 195",
	"C206": "Cessna 206 Stationair",
	"C207": "Cessna 207 Stationair 8",
	"C208": "Cessna 208 Caravan",
	"C210": "Cessna 210 Centurion",
	"C310": "Cessna 310",
	"C337": "Cessna 337 Skymaster",
	"C340": "Cessna 340A",
	"C404": "Cessna 404 Titan",
	"C414": "Cessna 414A Chancellor",
	"C421": "Cessna 421 Golden Eagle",
	"C441": "Cessna 441 Conquest II",
	"C25": "Cessna Citation CJ1",
	"C550": "Cessna Citation II",
	"C750": "Cessna Citation X",
	"O1": "Cessna L-19/O-1 Birddog",
	"C510": "Cessna Mustang",
	"T50": "Cessna T-50 Bobcat",
	"SR20": "Cirrus SR20",
	"SR22": "Cirrus SR22 G2",
	"COL4": "Columbia 400",
	"AC11": "Commander 112",
	"AC115": "Commander 115",
	"CAT": "Consolidated PBY5 Catalina",
	"CVLP": "Convair 340/440",
	"CVLT": "Convair 580",
	"C46": "Curtis C46",
	"FA7X": "Dassault Falcon 7X",
	"DHC7": "DeHavilland Dash 7",
	"DH8A": "DeHavilland Dash 8 100/200",
	"DH8C": "DeHavilland Dash 8 Q300",
	"DH89": "DeHavilland DH 89 Dragon Rapide",
	"DH82": "DeHavilland DH-82 Tiger Moth",
	"DOVE": "DeHavilland DH104 Dove",
	"HERN": "DeHavilland DH114 Heron",
	"DH80": "DeHavilland DH80A Puss Moth",
	"DHC1": "DeHavilland DHC-1 Chipmunk",
	"DHC2": "DeHavilland DHC-2 Beaver",
	"DH2T": "DeHavilland DHC-2 Turbo Beaver",
	"DHC3": "DeHavilland DHC-3 Otter",
	"DH3T": "DeHavilland DHC-3-T Turbo Otter",
	"DHC4": "DeHavilland DHC-4 Caribou",
	"DHC5": "DeHavilland DHC-5 Buffalo",
	"DHC6i": "DeHavilland DHC-6 300 Twin Otter (Aerosoft Extended)",
	"DHC6": "DeHavilland DHC-6 Twin Otter",
	"DA42": "Diamond DA-42 Twin Star",
	"DA20": "Diamond DA20 Katana",
	"DA40": "Diamond DA40D DiamondStar",
	"D228": "Dornier 228",
	"D328": "Dornier 328",
	"DO27": "Dornier Do-27 A4",
	"DO27b": "Dornier Do-27 B1",
	"DO28": "Dornier Do-28 A/B",
	"A26": "Douglas A-26",
	"C117": "Douglas C117D",
	"DC2": "Douglas DC-2",
	"DC2i": "Douglas DC-2 (FSX)",
	"DC3": "Douglas DC-3",
	"DC4M": "Douglas DC-4",
	"DC6": "Douglas DC-6",
	"DC6B": "Douglas DC-6B",
	"DC7B": "Douglas DC-7B",
	"DC7C": "Douglas DC-7C",
	"DC8": "Douglas DC-8 (10-40)",
	"EA50": "Eclipse 500",
	"E110": "Embraer 110",
	"E120": "Embraer 120",
	"E135": "Embraer ERJ-135LR",
	"E145": "Embraer ERJ-145LR",
	"E135l": "Embraer Legacy 600",
	"E50P": "Embraer Phenom 100",
	"ERCO": "ERCO Ercoupe 415-C",
	"AS50": "Eurocopter AS-350 Ecureuil",
	"BK17": "Eurocopter BK117",
	"EC20": "Eurocopter Colibri EC 120",
	"EC35": "Eurocopter EC-135",
	"FA24": "Fairchild 24R",
	"C119": "Fairchild C119",
	"C123": "Fairchild C123",
	"FSW3": "Fairchild Metro III",
	"FA62": "Fairchild PT19/26 Cornell",
	"F27": "Fokker F27-500 Friendship",
	"TRIM": "Ford Tri-Motor",
	"FBA2": "Found Bush Hawk",
	"GA8": "Gippsland GA8 Airvan",
	"GC1": "Globe Swift",
	"G44": "Grumman G-44 Widgeon",
	"G21": "Grumman G21 Goose",
	"HU16": "Grumman HU-16B Albatross",
	"S2P": "Grumman S2/C1",
	"AA5": "Grumman Tiger",
	"G21T": "Grumman Turbo Goose",
	"H25B": "Hawker 850XP",
	"A748": "Hawker Siddeley HS-748",
	"COUR": "Helio Super Courier H-295/U-10b",
	"DG15": "Howard DGA-15",
	"L37": "Howard Aero 500",
	"H500": "Hughes/McDonnell Douglas MD500E",
	"IL14": "Ilyushin Il-14",
	"IL18": "Ilyushin Il-18D",
	"JU52": "Junkers Ju-52",
	"MI8": "Kazan Helicopter Plant Mi-17-1V-GA",
	"LA25": "Lake Renegade",
	"LEG2": "Lancair Legacy",
	"LEG2i": "Lancair Legacy IV-P",
	"LJ45": "Lear 45",
	"LJ24": "Learjet 24B",
	"LJ24i": "Learjet 24B - Tip Tanks",
	"LJ25": "LearJet LJ25D",
	"L410": "Let L 410 UVP-E",
	"L410t": "Let L 410 UVP-T",
	"XL2": "Liberty XL2",
	"C130i": "Lockheed C-130 (Capt Sim)",
	"C130": "Lockheed C-130 (Generic)",
	"CONI": "Lockheed Constellation",
	"L10A": "Lockheed L10A Electra",
	"L10E": "Lockheed L10E Amelia Special",
	"L188": "Lockheed P-3C (L-188)",
	"L8": "Luscombe 8A",
	"M404": "Martin 404",
	"M7": "Maule M-7",
	"ME08": "Messerschmitt Bf 108 B",
	"M200": "Meyers 200D",
	"MU2B": "Mitsubishi MU-2B",
	"M20T": "Mooney M20 Bravo",
	"M20P": "Mooney M20 Juliet",
	"MS76": "Morane-Saulnier MS-760",
	"D25": "New Standard D25A",
	"NORS": "Noorduyn Norseman",
	"B25": "North American B-25",
	"P51": "North American P-51D Mustang",
	"T28": "North American T-28 Trojan",
	"SBR1": "North American T-39 Sabreliner",
	"T6": "North American T-6G Texan",
	"P750": "Pacific Aerospace 750XL",
	"P166": "Piaggio 166 Albatross",
	"P180": "Piaggio 180 Avanti",
	"P149": "Piaggio P-149D",
	"PC12": "Pilatus PC-12",
	"PC6": "Pilatus PC-6 Porter",
	"J3": "Piper J-3 Cub",
	"PA12": "Piper PA-12 Super Cruiser RTW",
	"PA18": "Piper PA-18 Super Cub",
	"PA20": "Piper PA-20 Pacer",
	"PA22": "Piper PA-22 Super Pacer",
	"PA22t": "Piper PA-22 Tri-Pacer",
	"PA23": "Piper PA-23 Apache",
	"PA23z": "Piper PA-23 Aztec",
	"PA24": "Piper PA-24 Comanche",
	"PA24i": "Piper PA-24 Comanche (A2A)",
	"P28A": "Piper PA-28 Archer",
	"P28R": "Piper PA-28 Arrow",
	"P28Ac": "Piper PA-28 Cherokee 180",
	"P28B": "Piper PA-28 Dakota",
	"P28Aw": "Piper PA-28 Warrior",
	"PA30": "Piper PA-30 Twin Comanche",
	"PA31": "Piper PA-31 Navajo",
	"PAY2": "Piper PA-31T Cheyenne II",
	"PAY1": "Piper PA-31T1 Cheyenne I/IA",
	"PAY2x": "Piper PA-31T2 Cheyenne IIXL",
	"PA32": "Piper PA-32 Cherokee Six/ Saratoga",
	"PA32t": "Piper PA-32 Saratoga TC",
	"PA34": "Piper PA-34 Seneca",
	"PA38": "Piper PA-38 Tomahawk",
	"PA42": "Piper PA-42-1000 Cheyenne 400",
	"PA44": "Piper PA-44 Seminole",
	"PA46": "Piper PA-46 Meridian",
	"PA60": "Piper PA-60 Aerostar",
	"PZ04": "PZL Wilga",
	"KODI": "Quest Kodiak",
	"CRER": "Rans S-7 Courier",
	"BE40": "Raytheon Beechjet / Hawker",
	"PRM1": "Raytheon Premier1",
	"RC3": "Republic Seabee",
	"DR40": "Robin DR400",
	"DR22": "Robin/Apex DR221",
	"R22": "Robinson R22",
	"R44": "Robinson R44",
	"AC11": "Rockwell Commander 114",
	"NAVI": "Ryan L-17 Navion",
	"SB20": "Saab 2000",
	"SF34": "Saab 340B",
	"SF90": "SAAB Scandia 90",
	"SH36": "Shorts SD3-60",
	"SC7": "Shorts Skyvan",
	"F260": "SIAI-Marchetti SF260",
	"SM19": "SIAI-Marchetti SM.1019A",
	"S43": "Sikorsky S-43",
	"S55": "Sikorsky S-55",
	"S76": "Sikorsky S-76",
	"TOBA": "Socata TB-10 Tobago",
	"TB20": "Socata TB21GT Trinidad",
	"TBM7": "Socata TBM 700",
	"TBM8": "Socata TBM 850",
	"SP7": "Spartan 7W Executive",
	"S108": "Stinson 108",
	"L5": "Stinson L-5B Sentinel",
	"RELI": "Stinson Reliant",
	"WALR": "Supermarine Walrus MK 1",
	"ECHO": "Tecnam P92 Echo",
	"T124": "Tupolev Tu-124",
	"RV7": "Van's RV-7/7A",
	"VISC": "Vickers Viscount",
	"WACF": "Waco Classic YMF",
	"S61": "Westland Seaking",
	"YK12": "Yakovlev Yak-12A",
	"YK18": "Yakovlev Yak-18T",
	"YK40": "Yakovlev Yak-40",
	"CH80": "Zenair CH 801",
	"Z43": "Zlin Z-43"}
	#"": "Aircreation 582SL",
	#"": "Boeing 221A Monomail",
	#"": "Boeing 247D",
	#"": "Bristol Mark 32 Superfreighter",
	#"": "Curtiss Robertson Robin J-1",
	#"": "Junkers W33 EW Flight",
	#"": "Junkers W33/34",
	#"": "Lockheed Vega",
	#"": "Zepplin NT"
	return dict

def getregiondict():
	dict={"Afghanistan": "Middle East",
	"Albania": "Europe",
	"Algeria": "Africa",
	"American Samoa": "Pacific",
	"Angola": "Africa",
	"Anguilla": "Caribbean",
	"Antarctica": "Antarctica",
	"Antigua and Barbuda": "Caribbean",
	"Argentina": "South America",
	"Armenia": "Europe",
	"Aruba": "Caribbean",
	"Ascension Island": "South America",
	"Australia": "Australia",
	"Austria": "Europe",
	"Azerbaijan": "Europe",
	"Bahamas, The": "Caribbean",
	"Bahrain": "Middle East",
	"Bangladesh": "Southeast Asia",
	"Barbados": "Caribbean",
	"Belarus": "Europe",
	"Belgium": "Europe",
	"Belize": "Central America",
	"Benin": "Africa",
	"Bermuda": "Caribbean",
	"Bhutan": "Southeast Asia",
	"Bolivia": "South America",
	"Bosnia and Herzegovina": "Europe",
	"Botswana": "Africa",
	"Brazil": "South America",
	"British Virgin Islands": "Caribbean",
	"Brunei": "Middle East",
	"Bulgaria": "Europe",
	"Burkina Faso": "Africa",
	"Burundi": "Africa",
	"Cambodia": "Southeast Asia",
	"Cameroon": "Africa",
	"Canada": "North America",
	"Cape Verde": "Africa",
	"Cayman Islands": "Caribbean",
	"Central African Republic": "Africa",
	"Chad": "Africa",
	"Chile": "South America",
	"China": "East Asia",
	"Colombia": "South America",
	"Comoros": "Africa",
	"Congo": "Africa",
	"Congo (DRC)": "Africa",
	"Congo DRC": "Africa",
	"Cook Islands": "Pacific",
	"Costa Rica": "Central America",
	"Cote d'Ivoire": "Africa",
	"Croatia": "Europe",
	"Cuba": "Caribbean",
	"Cyprus": "Europe",
	"Czech Republic": "Europe",
	"Denmark": "Europe",
	"Djibouti": "Africa",
	"Dominica": "Caribbean",
	"Dominican Republic": "Caribbean",
	"Ecuador": "South America",
	"Egypt": "Africa",
	"El Salvador": "Central America",
	"Equatorial Guinea": "Africa",
	"Eritrea": "Africa",
	"Estonia": "Europe",
	"Ethiopia": "Africa",
	"Falkland Islands (Islas Malvinas)": "South America",
	"Faroe Islands": "Europe",
	"Fiji Islands": "Pacific",
	"Finland": "Europe",
	"France": "Europe",
	"French Guiana": "South America",
	"French Polynesia": "Pacific",
	"Gabon": "Africa",
	"Gambia, The": "Africa",
	"Gaza Strip": "Middle East",
	"Georgia": "Europe",
	"Germany": "Europe",
	"Ghana": "Africa",
	"Gibraltar": "Europe",
	"Greece": "Europe",
	"Greenland": "North America",
	"Grenada": "Caribbean",
	"Guadeloupe": "Caribbean",
	"Guam": "Pacific",
	"Guatemala": "Central America",
	"Guinea": "Africa",
	"Guinea-Bissau": "Africa",
	"Guyana": "South America",
	"Haiti": "Caribbean",
	"Honduras": "Central America",
	"Hong Kong SAR": "East Asia",
	"Hungary": "Europe",
	"Iceland": "Europe",
	"India": "South Asia",
	"Indonesia": "Southeast Asia",
	"Iran": "Middle East",
	"Iraq": "Middle East",
	"Ireland": "Europe",
	"Israel": "Middle East",
	"Italy": "Europe",
	"Jamaica": "Caribbean",
	"Japan": "East Asia",
	"Jordan": "Middle East",
	"Kazakhstan": "Asia",
	"Kenya": "Africa",
	"Kiribati": "Pacific",
	"Korea": "East Asia",
	"Kuwait": "Middle East",
	"Kyrgyzstan": "Asia",
	"Laos": "Southeast Asia",
	"Latvia": "Europe",
	"Lebanon": "Middle East",
	"Lesotho": "Africa",
	"Liberia": "Africa",
	"Libya": "Africa",
	"Lithuania": "Europe",
	"Luxembourg": "Europe",
	"Macao SAR": "East Asia",
	"Macedonia, Former Yugoslav Republic of": "Europe",
	"Madagascar": "Africa",
	"Malawi": "Africa",
	"Malaysia": "Southeast Asia",
	"Maldives": "Pacific",
	"Mali": "Africa",
	"Malta": "Europe",
	"Marshall Islands": "Pacific",
	"Martinique": "Caribbean",
	"Mauritania": "Africa",
	"Mauritius": "Africa",
	"Mayotte": "Africa",
	"Mexico": "North America",
	"Micronesia": "Southeast Asia",
	"Moldova": "Europe",
	"Mongolia": "East Asia",
	"Morocco": "Africa",
	"Mozambique": "Africa",
	"Myanmar": "Southeast Asia",
	"Namibia": "Africa",
	"Nauru": "Pacific",
	"Nepal": "South Asia",
	"Netherlands Antilles": "Caribbean",
	"Netherlands, The": "Europe",
	"New Caledonia": "Pacific",
	"New Zealand": "Australia",
	"Nicaragua": "Central America",
	"Niger": "Africa",
	"Nigeria": "Africa",
	"Niue": "Pacific",
	"North Korea": "East Asia",
	"Northern Mariana Islands": "Pacific",
	"Norway": "Europe",
	"Oman": "Middle East",
	"Pakistan": "Middle East",
	"Panama": "Central America",
	"Papua New Guinea": "Southeast Asia",
	"Paraguay": "South America",
	"Peru": "South America",
	"Philippines": "Southeast Asia",
	"Poland": "Europe",
	"Portugal": "Europe",
	"Puerto Rico": "Caribbean",
	"Qatar": "Middle East",
	"Reunion": "Africa",
	"Romania": "Europe",
	"Russia": "Asia",
	"Rwanda": "Africa",
	"Samoa": "Pacific",
	"Sao Tome and Principe": "Africa",
	"Saudi Arabia": "Middle East",
	"Senegal": "Africa",
	"Serbia and Montenegro": "Europe",
	"Seychelles": "Africa",
	"Sierra Leone": "Africa",
	"Singapore": "Southeast Asia",
	"Slovakia": "Europe",
	"Slovenia": "Europe",
	"Solomon Islands": "Pacific",
	"Somalia": "Africa",
	"South Africa": "Africa",
	"Spain": "Europe",
	"Sri Lanka": "South Asia",
	"St. Kitts and Nevis": "Caribbean",
	"St. Lucia": "Caribbean",
	"St. Pierre and Miquelon": "Caribbean",
	"St. Vincent and the Grenadines": "Caribbean",
	"Sudan": "Africa",
	"Suriname": "South America",
	"Swaziland": "Africa",
	"Sweden": "Europe",
	"Switzerland": "Europe",
	"Syria": "Middle East",
	"Taiwan": "East Asia",
	"Tajikistan": "Asia",
	"Tanzania": "Africa",
	"Thailand": "Southeast Asia",
	"Timor-Leste": "Southeast Asia",
	"Togo": "Africa",
	"Tonga": "Pacific",
	"Trinidad and Tobago": "Caribbean",
	"Tunisia": "Africa",
	"Turkey": "Middle East",
	"Turkmenistan": "Asia",
	"Turks and Caicos Islands": "Caribbean",
	"Tuvalu": "Pacific",
	"Uganda": "Africa",
	"Ukraine": "Asia",
	"United Arab Emirates": "Middle East",
	"United Kingdom": "Europe",
	"United States": "North America",
	"Uruguay": "South America",
	"Uzbekistan": "Asia",
	"Vanuatu": "Pacific",
	"Venezuela": "South America",
	"Vietnam": "Southeast Asia",
	"Virgin Islands": "Caribbean",
	"Virgin Islands, British": "Caribbean",
	"Wallis and Futuna": "Pacific",
	"Yemen": "Middle East",
	"Zambia": "Africa",
	"Zimbabwe": "Africa"}
	return dict
