#!/usr/bin/python

def getregiondict():
	dict={'Afghanistan': 'Middle East',
	'Albania': 'Europe',
	'Algeria': 'Africa',
	'American Samoa': 'Pacific',
	'Angola': 'Africa',
	'Anguilla': 'Caribbean',
	'Antarctica': 'Antarctica',
	'Antigua and Barbuda': 'Caribbean',
	'Argentina': 'South America',
	'Armenia': 'Europe',
	'Aruba': 'Caribbean',
	'Ascension Island': 'South America',
	'Australia': 'Australia',
	'Austria': 'Europe',
	'Azerbaijan': 'Europe',
	'Bahamas, The': 'Caribbean',
	'Bahrain': 'Middle East',
	'Bangladesh': 'Southeast Asia',
	'Barbados': 'Caribbean',
	'Belarus': 'Europe',
	'Belgium': 'Europe',
	'Belize': 'Central America',
	'Benin': 'Africa',
	'Bermuda': 'Caribbean',
	'Bhutan': 'Southeast Asia',
	'Bolivia': 'South America',
	'Bosnia and Herzegovina': 'Europe',
	'Botswana': 'Africa',
	'Brazil': 'South America',
	'British Virgin Islands': 'Caribbean',
	'Brunei': 'Middle East',
	'Bulgaria': 'Europe',
	'Burkina Faso': 'Africa',
	'Burundi': 'Africa',
	'Cambodia': 'Southeast Asia',
	'Cameroon': 'Africa',
	'Canada': 'North America',
	'Cape Verde': 'Africa',
	'Cayman Islands': 'Caribbean',
	'Central African Republic': 'Africa',
	'Chad': 'Africa',
	'Chile': 'South America',
	'China': 'East Asia',
	'Colombia': 'South America',
	'Comoros': 'Africa',
	'Congo': 'Africa',
	'Congo (DRC)': 'Africa',
	'Congo DRC': 'Africa',
	'Cook Islands': 'Pacific',
	'Costa Rica': 'Central America',
	'Cote d'Ivoire': 'Africa',
	'Croatia': 'Europe',
	'Cuba': 'Caribbean',
	'Cyprus': 'Europe',
	'Czech Republic': 'Europe',
	'Denmark': 'Europe',
	'Djibouti': 'Africa',
	'Dominica': 'Caribbean',
	'Dominican Republic': 'Caribbean',
	'Ecuador': 'South America',
	'Egypt': 'Africa',
	'El Salvador': 'Central America',
	'Equatorial Guinea': 'Africa',
	'Eritrea': 'Africa',
	'Estonia': 'Europe',
	'Ethiopia': 'Africa',
	'Falkland Islands (Islas Malvinas)': 'South America',
	'Faroe Islands': 'Europe',
	'Fiji Islands': 'Pacific',
	'Finland': 'Europe',
	'France': 'Europe',
	'French Guiana': 'South America',
	'French Polynesia': 'Pacific',
	'Gabon': 'Africa',
	'Gambia, The': 'Africa',
	'Gaza Strip': 'Middle East',
	'Georgia': 'Europe',
	'Germany': 'Europe',
	'Ghana': 'Africa',
	'Gibraltar': 'Europe',
	'Greece': 'Europe',
	'Greenland': 'North America',
	'Grenada': 'Caribbean',
	'Guadeloupe': 'Caribbean',
	'Guam': 'Pacific',
	'Guatemala': 'Central America',
	'Guinea': 'Africa',
	'Guinea-Bissau': 'Africa',
	'Guyana': 'South America',
	'Haiti': 'Caribbean',
	'Honduras': 'Central America',
	'Hong Kong SAR': 'East Asia',
	'Hungary': 'Europe',
	'Iceland': 'Europe',
	'India': 'South Asia',
	'Indonesia': 'Southeast Asia',
	'Iran': 'Middle East',
	'Iraq': 'Middle East',
	'Ireland': 'Europe',
	'Israel': 'Middle East',
	'Italy': 'Europe',
	'Jamaica': 'Caribbean',
	'Japan': 'East Asia',
	'Jordan': 'Middle East',
	'Kazakhstan': 'Asia',
	'Kenya': 'Africa',
	'Kiribati': 'Pacific',
	'Korea': 'East Asia',
	'Kuwait': 'Middle East',
	'Kyrgyzstan': 'Asia',
	'Laos': 'Southeast Asia',
	'Latvia': 'Europe',
	'Lebanon': 'Middle East',
	'Lesotho': 'Africa',
	'Liberia': 'Africa',
	'Libya': 'Africa',
	'Lithuania': 'Europe',
	'Luxembourg': 'Europe',
	'Macao SAR': 'East Asia',
	'Macedonia, Former Yugoslav Republic of': 'Europe',
	'Madagascar': 'Africa',
	'Malawi': 'Africa',
	'Malaysia': 'Southeast Asia',
	'Maldives': 'Pacific',
	'Mali': 'Africa',
	'Malta': 'Europe',
	'Marshall Islands': 'Pacific',
	'Martinique': 'Caribbean',
	'Mauritania': 'Africa',
	'Mauritius': 'Africa',
	'Mayotte': 'Africa',
	'Mexico': 'North America',
	'Micronesia': 'Southeast Asia',
	'Moldova': 'Europe',
	'Mongolia': 'East Asia',
	'Morocco': 'Africa',
	'Mozambique': 'Africa',
	'Myanmar': 'Southeast Asia',
	'Namibia': 'Africa',
	'Nauru': 'Pacific',
	'Nepal': 'South Asia',
	'Netherlands Antilles': 'Caribbean',
	'Netherlands, The': 'Europe',
	'New Caledonia': 'Pacific',
	'New Zealand': 'Australia',
	'Nicaragua': 'Central America',
	'Niger': 'Africa',
	'Nigeria': 'Africa',
	'Niue': 'Pacific',
	'North Korea': 'East Asia',
	'Northern Mariana Islands': 'Pacific',
	'Norway': 'Europe',
	'Oman': 'Middle East',
	'Pakistan': 'Middle East',
	'Panama': 'Central America',
	'Papua New Guinea': 'Southeast Asia',
	'Paraguay': 'South America',
	'Peru': 'South America',
	'Philippines': 'Southeast Asia',
	'Poland': 'Europe',
	'Portugal': 'Europe',
	'Puerto Rico': 'Caribbean',
	'Qatar': 'Middle East',
	'Reunion': 'Africa',
	'Romania': 'Europe',
	'Russia': 'Asia',
	'Rwanda': 'Africa',
	'Samoa': 'Pacific',
	'Sao Tome and Principe': 'Africa',
	'Saudi Arabia': 'Middle East',
	'Senegal': 'Africa',
	'Serbia and Montenegro': 'Europe',
	'Seychelles': 'Africa',
	'Sierra Leone': 'Africa',
	'Singapore': 'Southeast Asia',
	'Slovakia': 'Europe',
	'Slovenia': 'Europe',
	'Solomon Islands': 'Pacific',
	'Somalia': 'Africa',
	'South Africa': 'Africa',
	'Spain': 'Europe',
	'Sri Lanka': 'South Asia',
	'St. Kitts and Nevis': 'Caribbean',
	'St. Lucia': 'Caribbean',
	'St. Pierre and Miquelon': 'Caribbean',
	'St. Vincent and the Grenadines': 'Caribbean',
	'Sudan': 'Africa',
	'Suriname': 'South America',
	'Swaziland': 'Africa',
	'Sweden': 'Europe',
	'Switzerland': 'Europe',
	'Syria': 'Middle East',
	'Taiwan': 'East Asia',
	'Tajikistan': 'Asia',
	'Tanzania': 'Africa',
	'Thailand': 'Southeast Asia',
	'Timor-Leste': 'Southeast Asia',
	'Togo': 'Africa',
	'Tonga': 'Pacific',
	'Trinidad and Tobago': 'Caribbean',
	'Tunisia': 'Africa',
	'Turkey': 'Middle East',
	'Turkmenistan': 'Asia',
	'Turks and Caicos Islands': 'Caribbean',
	'Tuvalu': 'Pacific',
	'Uganda': 'Africa',
	'Ukraine': 'Asia',
	'United Arab Emirates': 'Middle East',
	'United Kingdom': 'Europe',
	'United States': 'North America',
	'Uruguay': 'South America',
	'Uzbekistan': 'Asia',
	'Vanuatu': 'Pacific',
	'Venezuela': 'South America',
	'Vietnam': 'Southeast Asia',
	'Virgin Islands': 'Caribbean',
	'Virgin Islands, British': 'Caribbean',
	'Wallis and Futuna': 'Pacific',
	'Yemen': 'Middle East',
	'Zambia': 'Africa',
	'Zimbabwe': 'Africa'}
	return dict
	
